config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :games
  get 'entrance/index'

  devise_for :users
  get 'home/index'

  root 'entrance#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :admin, :all
    elsif user.member?
      can :member, :all
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  enum status: { preparation: 0, session: 1, liquidation: 2, finish: 3 }
  has_many :passengers, dependent: :destroy
  has_many :users, through: :passengers
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: {member: 0, admin: 1}
  validates :name, presence: true, length: { maximum: 50 }
  has_many :passengers, dependent: :destroy
  has_many :games, through: :passengers

  after_initialize :set_default, if: :new_record?

  private
  def set_default
    self.role ||= :member
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update ) << :name
      devise_parameter_sanitizer.for(:sign_up) << :role
      devise_parameter_sanitizer.for(:account_update ) << :role
    end
end

app/controllers/entrance_controller.rb
class EntranceController < ApplicationController
  def index
    @games = Game.all
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:startTime, :term, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @games = Game.where(status: 'preparation')
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:name, :starCount, :money, :debt, :g_count, :c_count, :p_count, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrance_helper.rb
module EntranceHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/entrance/index.html.haml
%h1 Espoir GCP
%h2 希望の船にようこそ
%p
  Espoir GCPは、船上での一風変わったジャンケンを楽しめるオンラインゲームです。

- if user_signed_in?
  Logged in as
  %strong
    = current_user.email
  &nbsp;
  %strong
    name:
    = current_user.name
  = link_to "Settings", edit_user_registration_path, :class => "navbar-link"
  |
  = link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link"
- else
  = link_to "Sign up", new_user_registration_path, :class => "navbar-link"
  |
  = link_to "Login", new_user_session_path, :class => "navbar-link"

- if current_user
  - if can? :admin, current_user
    %p admin information
  - if can? :member, current_user
    %p member information

%h2 開催中のゲーム
%table
  %thead
    %tr
      %th 開始時刻
      %th 開催期間（分）
      %th 状態

  %tbody
    - @games.each do |game|
      %tr
        %td= game.startTime
        %td= game.term
        %td= game.status

app/views/games/_form.html.haml
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :startTime
    = f.datetime_select :startTime
  .field
    = f.label :term
    = f.number_field :term
  .actions
    = f.submit 'Save'

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Listing games

%table
  %thead
    %tr
      %th Starttime
      %th Term
      %th Status
      %th
      %th
      %th

  %tbody
    - @games.each do |game|
      %tr
        %td= game.startTime
        %td= game.term
        %td= game.status
        %td= link_to 'Show', game
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice

%p
  %b Starttime:
  = @game.startTime
%p
  %b Term:
  = @game.term
%p
  %b Status:
  = @game.status

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

app/views/home/index.html.haml
%h1 ホーム ― 船着き場
- if user_signed_in?
  Logged in as
  %strong
    = current_user.email
  = link_to "Settings", edit_user_registration_path, :class => "navbar-link"
  |
  = link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link"
- else
  = link_to "Sign up", new_user_registration_path, :class => "navbar-link"
  |
  = link_to "Login", new_user_session_path, :class => "navbar-link"

%p
  ようこそいらっしゃいました。
  %br/
  ご希望の船に御乗り下さい。

%h2 参加者募集中の船
%table
  %thead
    %tr
      %th 開始時刻
      %th 開催期間（分）
      %th 状態
      %th 乗船手続

  %tbody
    - @games.each do |game|
      %tr
        %td= game.startTime
        %td= game.term
        %td= game.status
        %td 手続開始

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EspoirGcp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      %p.alert.alert-success
        = notice
    - if alert
      %p.alert.alert-danger
        = alert
    = yield

app/views/passengers/_form.html.haml
= form_for @passenger do |f|
  - if @passenger.errors.any?
    #error_explanation
      %h2= "#{pluralize(@passenger.errors.count, "error")} prohibited this passenger from being saved:"
      %ul
        - @passenger.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :starCount
    = f.number_field :starCount
  .field
    = f.label :money
    = f.number_field :money
  .field
    = f.label :debt
    = f.number_field :debt
  .field
    = f.label :g_count
    = f.number_field :g_count
  .field
    = f.label :c_count
    = f.number_field :c_count
  .field
    = f.label :p_count
    = f.number_field :p_count
  .field
    = f.label :location
    = f.number_field :location
  .actions
    = f.submit 'Save'

app/views/passengers/edit.html.haml
%h1 Editing passenger

= render 'form'

= link_to 'Show', @passenger
\|
= link_to 'Back', passengers_path

app/views/passengers/index.html.haml
%h1 Listing passengers

%table
  %thead
    %tr
      %th Name
      %th Starcount
      %th Money
      %th Debt
      %th G count
      %th C count
      %th P count
      %th Location
      %th
      %th
      %th

  %tbody
    - @passengers.each do |passenger|
      %tr
        %td= passenger.name
        %td= passenger.starCount
        %td= passenger.money
        %td= passenger.debt
        %td= passenger.g_count
        %td= passenger.c_count
        %td= passenger.p_count
        %td= passenger.location
        %td= link_to 'Show', passenger
        %td= link_to 'Edit', edit_passenger_path(passenger)
        %td= link_to 'Destroy', passenger, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Passenger', new_passenger_path

app/views/passengers/new.html.haml
%h1 New passenger

= render 'form'

= link_to 'Back', passengers_path

app/views/passengers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @passenger.name
%p
  %b Starcount:
  = @passenger.starCount
%p
  %b Money:
  = @passenger.money
%p
  %b Debt:
  = @passenger.debt
%p
  %b G count:
  = @passenger.g_count
%p
  %b C count:
  = @passenger.c_count
%p
  %b P count:
  = @passenger.p_count
%p
  %b Location:
  = @passenger.location

= link_to 'Edit', edit_passenger_path(@passenger)
\|
= link_to 'Back', passengers_path